name: Test Checkout

on: push

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
