name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch you want to deploy to (GitHub Pages branch)
        folder: . # The folder the action should deploy (current directory of your project)

    # Add additional steps for deployment or other tasks
